### ISSUE TITLE
Shard package tests take 17 sec to run

### ISSUE THREAD

**Issue by rShetty** [gojektech/weaver#12]
- Investigate the cause and fix it

**Comment by gwthm-in** [comment]
Ran sampling on tests. Uniform sharding test is taking longer time to run. Should test this in alternative way. Here is the [test](https://github.com/gojektech/weaver/blob/e135a0f99c56cf89de16981deef8f33966bd7a3f/pkg/shard/hashring_test.go#L315-L354) that taking more time. 

```shell
$  time go test -run TestShouldShardUniformally
PASS
ok  	github.com/gojektech/weaver/pkg/shard	11.539s
go test -run TestShouldShardUniformally  13.47s user 0.75s system 112% cpu 12.585 total
```
