### ISSUE TITLE
Sometimes tests are stuck for longer time. 

### ISSUE THREAD

**Issue by gwthm-in** [gojektech/weaver#24]
Sometimes when running tests, they are stuck for longer time, couldn't get them to complete. 

```
╭─TheInsider ~/Documents/repos/gojektech/weaver ‹ruby-2.5.0› ‹weaver-cli*›
╰─➤  mk test
cp weaver.conf.yaml.sample weaver.conf.yaml
GO111MODULE=on go test ./...
ok  	github.com/gojektech/weaver	(cached)
?   	github.com/gojektech/weaver/cmd/weaver	[no test files]
ok  	github.com/gojektech/weaver/config	0.021s
^C{"level":"info","msg":"bootstrapping router using etcd on /weaver/acls/","time":"2019-03-19T07:53:25+05:30"}
{"level":"info","msg":"creating router namespace on etcd using /weaver/acls/","time":"2019-03-19T07:53:25+05:30"}
FAIL	github.com/gojektech/weaver/etcd	14.251s
make: *** [Makefile:40: test] Error 1
```
Here is the message, that I got when trying to reproduce it.

**Comment by MuthukumarHelios** [comment]
I think this is because of viper Config [code ref](https://github.com/gojektech/weaver/blob/master/config/config.go#L53)
If you fake your viper call the test case will pass

**Comment by rShetty** [comment]
Closing this, this is issue with connectivity to etcd. please check the etcd connectivity and reraise the issue, if the issue persists
